### DISCUSSION TITLE
AWS Lambda adapter (V1): Non-root path

### DISCUSSION THREAD

**Discussion by chinanderm** [trpc/trpc#4381] [Q&A] [answered]
I'm working to incrementally adopt tRPC into a AWS Lambda/Serverless project but am running into an issue from the jump. Rather than having the tRPC queries and mutations available immediately at the root of my service URL (`/*`), like in the adapter example, I'd like to put them at `/trpc/*`. However I'm having a hard time figuring out the best way to do that without duplicating the `trpc/*` in the query/procedure function name.

How can I set the config so that the tRPC queries/mutations are called at `/trpc/*` but I don't have to name the function `'trpc/getHelloWorld'`? I'm using V1/REST APIs. For V2/HTTP APIs, the starting path is ignored and I do not need to prefix all procedure function names.

serverless.yml:
```yml
...
functions:
  ...
  trpc:
    handler: server.trpcHandler
    events:
      - http:
          path: trpc/{proxy+}
          method: get
      - http:
          path: trpc/{proxy+}
          method: post
...
```

server.ts
```typescript
export const trpcInstance = initTRPC.create()

const appRouter = trpcInstance.router({
  'trpc/getHelloWorld': trpcInstance.procedure.input(z.string()).query((opts) => {
    return `Hello ${opts.input}!`
  }),
})

export type AppRouter = typeof appRouter

const createContext = (
  context: CreateAWSLambdaContextOptions<APIGatewayProxyEvent>
) => ({
  // no context
})

export const trpcHandler = awsLambdaRequestHandler({
  router: appRouter,
  createContext,
})
```

It appears `awsLambdaRequestHandler` uses `event.path` as-is and doesn't allow for an option to specify a prefix. Maybe it could allow for something like this?
```typescript
awsLambdaRequestHandler({
  router: appRouter,
  createContext,
  pathPrefix: '/trpc'
})
```
